version: '3'
services:
  frontend:
    build: .
    ports:
      - "3001:3000"  # Change the host port to 3001 to avoid conflicts
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
