version: '3.8'

services:
  frontend:
    build: ./Frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  backend:
    build: ./Server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret
      - PGUSER=postgres
      - PGHOST=your_postgres_host
      - PGDATABASE=SCRC-ACCESS
      - PGPASSWORD=postgres
      - PGPORT=5432
